### ISSUE TITLE
Add option to have Tabs collapse to hamburger at a given breakpoint

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1001]

**Comment by tesk9** [comment]
Discussed in Bat Chat Feb 14, 2023.

We decided that rather than collapsing to a select, we'd like to pursue more of a classic "hamburger" pattern, where the tablist is hidden behind an interaction (although we would like the currently-selected tab to be visible).

We're interested in exploring having the tabs and sidenav component possibly sharing a collapse/expand implementation to some degree.

**Comment by krinhorn** [comment]
Here's how Canvas hamburgers while also showing the current page title and allowing for submenus:
![image](https://user-images.githubusercontent.com/31359690/218819289-b2162bb3-4640-4d64-bea8-6517db059527.png)
![image](https://user-images.githubusercontent.com/31359690/218819300-98c2521e-e431-47ed-b91c-3c871d86cacf.png)
![image](https://user-images.githubusercontent.com/31359690/218819307-c5967191-62bf-432f-b42f-020c6f5c86f9.png)
![image](https://user-images.githubusercontent.com/31359690/218819411-97fe1cd6-4af8-4866-8041-34747449210a.png)

**Comment by bendansby** [comment]
Given that we only have a few tabs at any given time, simply moving to a vertical layout may be sufficient for this issue: https://github.com/NoRedInk/noredink-ui/pull/1422
