### ISSUE TITLE
Menu: add theme matching Button.tertiary

### ISSUE THREAD

**Issue by bendansby** [NoRedInk/noredink-ui#1189]

**Comment by tesk9** [comment]
So I think what I'd like to do instead is change the Menu API so that it sets up attributes to attach to the triggering button, but it doesn't control the styles of the button. I've started on adding ["rightIcon" helpers](https://github.com/NoRedInk/noredink-ui/pull/1188) to ClickableSvg, ClickableText, and Button, which I think is the only real blocker (since we need a nice disclosure/dialog indicator).  Anyway then the tertiary and quaternary and whatever else styles should all be options. 

Does that sound reasonable, or am I forgetting something important about the menu trigger element...?

**Comment by bendansby** [comment]
Seems reasonable! As long as it doesn't end up too convoluted from a dev perspective

**Comment by tesk9** [comment]
Is there anything left on this issue? I think it's done, right?

**Comment by bendansby** [comment]
Yes!
