### ISSUE TITLE
Tabs.V4

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#300]
Often, when using Tabs, the caller needs to do something like this:

```
   model.tabs
                        |> Zipper.first
                        |> Zipper.find (.id >> (==) tabId)
                        |> Maybe.withDefault model.tabs
```
because the Tabs API asks for `{ onSelect : id -> msg, ...}`

I think it might be nicer to have an API like this:

```
type alias Tabs =
    Zipper (Tab id) 

init : List (Tab id) -> Tab id -> List (Tab id) -> Tabs
init = 
    Zipper.Zipper

type alias Config id msg =
    { title : Maybe String
    , onSelect : Tabs -> msg
    , tabs : Tabs
    , content : id -> Html msg
    , alignment : Alignment
    }
```
So that the caller doesn't need to know about List.Zipper or touch it.

**Comment by avh4** [comment]
On curriculum library, the design spec requires that sometimes no tab be selected -- so I think we'll have to not use a zipper to implement that.

Also, I think that it's generally turned out to be not ideal to store the UI state (which tab is selected) mixed together with the static data (the objects which are being represented by tabs),  so I really think the component should take a `List Tab` and `selected : Maybe id` instead of a zipper.

**Comment by tesk9** [comment]
I looked around in the curriculum library product spec, and I don't fully understand what it would mean for there not to be a selected tab. Would the tabs still show, but without a rendered tab panel? just empty space?

**Comment by avh4** [comment]
It's when the teacher is searching:  https://paper.dropbox.com/doc/Product-Spec-Curriculum-Library--AfiLHS1XYUJAoIoXIGF3_auvAg-CHaw3XzNKq4MePdinHDRc#:uid=054397348133745218381189&h2=Search  the three normal tabs show, but none of them are selected.  There is a rendered content area for the search results, and it's under the tab bar -- just none of the tabs appear selected.  (Maybe for accessibility purposes there is actually a selected "Search" tab, but it's invisible to sighted users?)

**Comment by tesk9** [comment]
Ahh, thanks! I think that makes sense, yeah!
