### ISSUE TITLE
Move Nri.Outline and Nri.Outline.Keyed to noredink-ui

### ISSUE THREAD

**Issue by tesk9** [NoRedInk/noredink-ui#499]

**Comment by BrianHicks** [comment]
I looked at doing this today and it ended up being to big for the time I have. For a future person:

- this needs Nri.Outline and Nri.Outline.Keyed
- those use Nri.Outline.Utils, which will need to be ported but private
- they also use Nri.Palette, which after glancing between that and Nri.Ui.Palette.V1 I think would just be a drop-in.

I made some ASCII art for the docs because I couldn't remember what parts did what. Here they are:

For `view`:

    ┌─ Title ──────────────────────────────┐
    │                                      │
    │  Content content content             │
    │                                      │
    └──────────────────────────────────────┘
    ┌─ Title ──────────────────────────────┐
    │                                      │
    │  Content content content             │
    │                                      │
    └──────────────────────────────────────┘

for `row`:

    ┌─ Title ──────────────────────────────┐
    │                                      │
    │  Content content content             │
    │                                      │
    └─┬────────────────────────────────────┘
      │ ┌─ Child #1 ───────────────────────┐
      │ │                                  │
      ├─┤                                  │
      │ │                                  │
      │ └──────────────────────────────────┘
      │ ┌─ Child #2 ───────────────────────┐
      │ │                                  │
      └─┤                                  │
        │                                  │
        └──────────────────────────────────┘

I also think `row` could be html-likeified. It has a bunch of variations, one of which basically just exposes the `Outline` constructor.
